# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f22323a2e91e5bb9ab7d6f7b0ba6606b68cd713b50c142dc6a01e8ec8e965ee77c64cc1797773d44d12054a3ed04660f9e33868cc10cd873acdcfd67c9e71d1d

test:
  secret_key_base: c10e5a8771d7555512be0e463e88886ea9a882db4f0d18729e9c1ca4c7bdeaa3bd5db4ea2d755c08e39ccb26d5cedde9202b3843c85a4110f955a199d1e10883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
